### ISSUE TITLE
Possible inconsistency in `PeerCompare`

### ISSUE THREAD

**Issue by schomatis** [ipfs/go-peertaskqueue#9]
There are basically two dimensions we judge: pending and active work (ignoring freeze). The end of the function would seem to indicate the priority is on the active work (deferring to pending only in case of tie).

https://github.com/ipfs/go-peertaskqueue/blob/0d567453333974bb0639dbbaff5740f6d5718dc7/peertracker/peertracker.go#L94-L103

But the start of the function, eagerly dealing with the zero edge case, gives in this case more weight to the pending tasks.

https://github.com/ipfs/go-peertaskqueue/blob/0d567453333974bb0639dbbaff5740f6d5718dc7/peertracker/peertracker.go#L79-L84

(I'm conflating task count with task work here for ease of explanation.)

**Comment by schomatis** [comment]
This may not be an issue (at least for the BitSwap case I'm looking at) since no pending tasks would mean there is no work to do for that peer so we would never want to pop that `PeerTracker` as we'd have no work attached to it.

**Comment by Stebalien** [comment]
Yep. This is intentional, IIRC. We sort peers with pending tasks before peers without pending tasks because there's no work for peers without pending tasks.

Later, if we have two peers with an equal number of active tasks, we pick the peer with more pending tasks.
